
/*
	//	var  obj= angular.module("salesApp");
		obj.controller('quoteCtrl', function($scope){
			$scope.addQuote=false;
			$scope.quotationList = [{id: 'choice1', name: 'choice1'}, {id: 'choice2', name: 'choice2'}, {id: 'choice3', name: 'choice3'}];
			
			$scope.addQuotation = function(){
				$scope.addQuote=true;
			};
			
		});
		
	http://www.concretepage.com/spring-4/consume-restful-web-service-using-angularjs-spring-4-rest-json-with-ngresource-and-http-example	
	http://www.concretepage.com/spring-4/spring-mvc-4-rest-angularjs-hibernate-4-integration-crud-tutorial-with-ngresource-example
//var app = angular.module("salesApp", []);

 */
 
 
  // var objres = angular.module('salesApp', ['ngResource']);
	// obj.factory('showVendor', ['$resource', function ($resource) {
		// return $resource('http://localhost:8080/dman/mm',
			// {
				// update:{method:'PUT'},
				// get:    {method:'GET'},
				// save:   {method:'POST'}
			// }, 
            // {
                // stripTrailingSlashes: false
            // }
		// );
	// }]);
 
 // QUOTATION FORM CONTROLLERS
 //================================================================
 obj.controller("quoteCtrl", function($scope){
	$scope.showChoiceLabel=false;
	$scope.topHeader=false;
	$scope.topDetail=false;
	$scope.quotationList=[];
	$scope.quotRef=[
		{ref:"Reference 1"},
		{ref:"Reference 2"},
		{ref:"Reference 3"}
	];
	$scope.quotgenRef=[
		{ref:"Generated By1"},
		{ref:"Generated By2"},
		{ref:"Generated By3"}
	];
	$scope.fincyear=[
		{ref:"2014-2015"},
		{ref:"2015-2016"},
		{ref:"2016-2017"},
		{ref:"2017-2018"}
	];
	$scope.addNewChoice = function(showAdd){
		$scope.showChoiceLabel=true;
		$scope.topHeader=true;
		$scope.topDetail=true;
		var newItemNo = $scope.quotationList.length+1;
		console.log(newItemNo);
		$scope.quotationList.push({
			itemId: '',
			itemName:'',
			UOM:'',
			quantity:0,
			unitPrice:0,
			amount:0,
			
		});
		
		console.log($scope.quotationList);
	};
	
	
	$scope.removeNewChoice = function (index){
		newItemNo = $scope.quotationList.length-1;
		$scope.quotationList.splice(index,1);
		console.log(newItemNo);
		if(newItemNo==0)
		{
			//$scope.showChoiceLabel=false;
			$scope.topHeader=false;
			$scope.topDetail=false;
		}
		
	
	/*	$scope.quotationList.pop({
			itemId: '',
			itemName:'',
			UOM:'',
			quantity:'',
			unitPrice:'',
			amount:'',
			
		});*/
		
	};
});


// PURCHASE ORDER FORM CONTROLLERS
 //================================================================
obj.controller("purchCrtl", function($scope){
	$scope.showPOform=false;
	$scope.topHeader=false;
	$scope.topDetail=false;
	$scope.quotationList=[];
	$scope.quotRef=[
		{ref:"Reference 1"},
		{ref:"Reference 2"},
		{ref:"Reference 3"}
	];
	
	$scope.fincyear=[
		{ref:"2014-2015"},
		{ref:"2015-2016"},
		{ref:"2016-2017"},
		{ref:"2017-2018"}
	];
	$scope.addNewChoice = function(showAdd){
		$scope.showPOform=true;
		$scope.topHeader=true;
		$scope.topDetail=true;
		var newItemNoPo = $scope.quotationList.length+1;
		console.log(newItemNoPo);
		$scope.quotationList.push({
			itemId: '',
			itemName:'',
			UOM:'',
			quantity:0,
			unitPrice: 0,
			discount:0,
			amount:0,
		});
	};
	$scope.removeNewChoice = function (index){
		newItemNoPo = $scope.quotationList.length-1;
		$scope.quotationList.splice(index,1);
		console.log(newItemNoPo);
		if(newItemNoPo==0)
		{
			//$scope.showChoiceLabel=false;
			$scope.topHeader=false;
			$scope.topDetail=false;
		}
		
		/*$scope.quotationList.pop({
			itemId: '',
			itemName:'',
			UOM:'',
			quantity:0,
			unitPrice: 0,
			discount:0,
			amount:0,
			
		});*/
		
	};
});



// INWARD DELIVERY CHALLAN FORM CONTROLLERS
 //================================================================
obj.controller("idcCtrl", function($scope){
	$scope.InwardDC=false;
	$scope.topHeader=false;
	$scope.topDetail=false;
	$scope.InwardDCList=[];
	$scope.fincyear=[
		{ref:"2014-2015"},
		{ref:"2015-2016"},
		{ref:"2016-2017"},
		{ref:"2017-2018"}
	];
	
	$scope.addNewChoice = function(showAdd){
		$scope.InwardDC=true;
		$scope.topHeader=true;
		$scope.topDetail=true;
		var newItemNo = $scope.InwardDCList.length+1;
		console.log(newItemNo);
		$scope.InwardDCList.push({
			itemId: '',
			itemName:'',
			quantity:0,
			unitPrice: 0,
			amount:0,
			
		});
	};

	$scope.removeNewChoice = function (index){
		newItemNo = $scope.InwardDCList.length-1;
		$scope.InwardDCList.splice(index,1);
		console.log(newItemNo);
		if(newItemNo==0)
		{
			//$scope.showChoiceLabel=false;
			$scope.topHeader=false;
			$scope.topDetail=false;
		}
		
	/*	$scope.InwardDCList.pop({
			itemId: '',
			itemName:'',
			quantity:0,
			unitPrice: 0,
			amount:0,
			
		});	*/
		
	};
});





// VENDOR FORM CONTROLLERS
 //================================================================
 /*
obj.controller("vendorCrtl", ['$scope','showVendor', function($scope, showVendor){
	//$scope.showVendor=false;
	$scope.vendorAddNew=false;
	$scope.availableVendors = false;
	$scope.venDetails=false;
	$scope.venaddDetails=false;
	$scope.venFullAddress=[];
	$scope.venAddress2=[];
	//$scope.VendorList=[];
	
	$scope.showNewItem = function(vendorItem){
		$scope.vendorAddNew=true;
		$scope.modalBt=true;
		$scope.availableVendors = false;
		$scope.delAddButton=false;
		$scope.afterModal=false;
	
		console.log(vendorItem);
	};
	
	$scope.addFullDet = function(index){
		$scope.ModalBody=true;
		$scope.venaddDetails=false;
		$scope.afterModal=false;
		var Ven = $scope.venFullAddress.length+1;
		
		$scope.venFullAddress.push({
			personName:'',
			mobileNum:'',
			workNum:'',
			emailid:'',
			
		});
		var Ven2 = $scope.venAddress2.length+1;
		$scope.venAddress2.push({
			personName:'',
			mobileNum:'',
			workNum:'',
			emailid:'',
			
		});
		console.log(Ven);
		console.log(Ven2);
		
	};
	

	$scope.addFullDet = function(index){
		$scope.ModalBody=true;
		$scope.venaddDetails=false;
		var Ven = $scope.venFullAddress.length+1;
		
		$scope.venFullAddress.push({
			personName:'',
			mobileNum:'',
			workNum:'',
			emailid:'',
			
		});
		// $scope.modalBt=false;
		// var Ven2 = $scope.venAddress2.length+1;
		// $scope.venAddress2.push({
			// personName:'',
			// mobileNum:'',
			// workNum:'',
			// emailid:'',
			
		// });
		console.log(Ven);
		console.log(Ven2);
		
	};
	
	$scope.dataAfterModal = function(){
		$scope.afterModal=true;
		$scope.enEdit=true;
		$scope.modalBt=false;
		
		//$scope.venaddDetails=true;
		//$scope.venAddress=[];
		// newItemVen = $scope.venAddress.length+1;
		// $scope.venAddress.push({
			// personName:'',
			// mobileNum:'',
			// workNum:'',
			// emailid:'',
			
		// });
		
	};
	
	$scope.addContDet = function(index){
		$scope.venaddDetails=true;
		var downAdd= $scope.venAddress2.length+1;
		$scope.venAddress2.push({
			addressLine1:'',
			addressLine2:'',
			addressLine3:'',
			city:'',
			state:'',
			pincode:'',
			
		});
		
		
	};
	
	$scope.saveVenFormData = function(){
		
		// console.log();
		console.log($scope.addVen);
		console.log($scope.newVendorDetails);
		// console.log();
		
	};
	
	
/*	
	$scope.addAddMore = function(index){
		//$scope.venDetails=true;
		$scope.venaddDetails=true;
		$scope.delAddButton=true;
		//$scope.venAddress=[];
		
		newItemVen2 = $scope.venAddress2.length+1;
		$scope.venAddress2.push({
			addressLine1:'',
			city:'',
			state:'',
			pincode:'',
			
		});
		console.log(index);
		//console.log(newItemVen2);
	};
	
	$scope.delAdd = function(index){
	//	newItemVen2 = $scope.venAddress2.length-1;
		$scope.venAddress2.splice(index,1);
		if(index<=1){
			$scope.delAddButton=false;
		}
		else{
			
		}
		console.log(index);
		console.log(newItemVen2);
		
	};
	*/
	/*
	$scope.showSearch = function(vendorItem) {
		$scope.vendorAddNew=false;
		$scope.venDetails=false;
		$scope.venaddDetails=false;
		$scope.venFullAddress=[];
		$scope.venAddress2=[];
		$scope.searchRes = true;
		$scope.availableVendors = true;
		
		console.log(vendorItem);
	}
	//
	// Resource Sharing
	var ob = this;
	ob.venFullAddress = [];
	ob.venAddress2 = [];
	ob.vend = new showVendor(); 
    ob.fetchAllVendors = function(){
        ob.venFullAddress = showVendor.query();
    };
	
	$scope.saveVenFormData = function(){
		console.log("Inside Save Function");
		
		if($scope.vendorForm.$valid){
			ob.showVendor.$save(function(vendorForm){
				console.log(vend); 
				 ob.flag= 'created';	
				// ob.reset();	
				 ob.fetchAllVendors();
				},
				function(err){
				 console.log(err.status);
				 ob.flag='failed';
				}
			);
		}
		
	};
	
	
	/*
		REMOVING VENDOR - TRIGGER FROM VENDOR LIST (EDIT AND DELETE)
	
		$scope.removeNewChoice = function (showAdd){
		newItemNo = $scope.VendorList.length-1;
		console.log(newItemNo);
		
		if(newItemNo==0)
		{
			//$scope.showChoiceLabel=false;
			$scope.topHeader=false;
			$scope.topDetail=false;
		}
		$scope.VendorList.pop();
		
		$scope.VendorList.pop({
			itemId: '',
			itemName:'',
			UOM:newItemNo,
			quantity:0,
			unitPrice: 0,
			amount:0,
			
		});
		
	};*/
// }]);


//
// 		INVOICE FORM CONTROLLER
//
obj.controller("invoiceCrtl", function($scope){
	$scope.showInvoiceform=false;
	$scope.topHeader=false;
	$scope.topDetail=false;
	$scope.invList=[];
	$scope.fincyear=[
		{ref:"2014-2015"},
		{ref:"2015-2016"},
		{ref:"2016-2017"},
		{ref:"2017-2018"}
	];
	$scope.taxes=[
		{tax:"14.2%"},
		{tax:"5.2"}
	];
	$scope.addNewChoice = function(showAdd){
		$scope.showInvoiceform=true;
		$scope.topHeader=true;
		$scope.topDetail=true;
		var newItemNoPo = $scope.invList.length+1;
		console.log(newItemNoPo);
		$scope.invList.push({
			itemId: '',
			itemdesc:'',
			quantity:0,
			unitPrice: 0,
			discount:0,
			tax:'',
			amount:0,
		});
	};
	$scope.removeNewChoice = function (index){
		newItemNoPo = $scope.invList.length-1;
		$scope.invList.splice(index,1);
		console.log(newItemNoPo);
		if(newItemNoPo==0)
		{
			//$scope.showChoiceLabel=false;
			$scope.topHeader=false;
			$scope.topDetail=false;
		}
		
	};
});



/* 
 obj.controller("quoteCtrl", function($scope) {
   $scope.showChoiceLabel=false;
   //$scope.newItemNo=1;
   $scope.length=0;
   $scope.quotationList = [{}];
   
   $scope.addNewChoice = function() {
	   $scope.showChoiceLabel=true;
     var newItemNo = $scope.quotationList.length+1;
     $scope.quotationList.push({'id' : '' + newItemNo, 'name' : '' + newItemNo, 'uom':''+ newItemNo, 'qty' :'' + newItemNo});
   };
   
   $scope.removeNewChoice = function() {
     var newItemNo = $scope.quotationList.length-1;
     if ( newItemNo >= 0 ) {
      $scope.quotationList.pop();
     }
   };
   
   $scope.showAddChoice = function(choice) {	   
     return choice.id === $scope.quotationList[$scope.quotationList.length-1].id;
	};
   
 });

 
 
 // INWARD DELIVERY CHALLAN FORM CONTROLLERS
 //================================================================
 obj.controller("idcCtrl", function($scope) {
   $scope.InwardDC=false;
   //$scope.newItemNo=1;
   $scope.length=0;
   $scope.InwardDCList = [{}];
   
   $scope.addNewChoice = function() {
	   $scope.InwardDC=true;
     var newItemNo = $scope.InwardDCList.length+1;
     $scope.InwardDCList.push({'id' : '' + newItemNo, 'name' : '' + newItemNo, 'uom':''+ newItemNo, 'qty' :'' + newItemNo});
   };
   
   $scope.removeNewChoice = function() {
     var newItemNo = $scope.InwardDCList.length-1;
     if ( newItemNo >= 0 ) {
      $scope.InwardDCList.pop();
     }
   };
   
   $scope.showAddChoice = function(choice) {	   
     return choice.id === $scope.InwardDCList[$scope.InwardDCList.length-1].id;
   };
   
 });
 
 */